[package]
name = "typeracer"
version = "0.0.1"
edition = "2021"
default-run = "typeracer"
authors = [ "alexzanderr <alexzander.dot.dev@gmail.com>" ]
exclude = [
    "python_version"
]

[features]
music = []

[dependencies.core-dev]
git = "https://github.com/alexzanderr/rust-core-dev"
features = [
    "datetime",
    "traits",
    "terminal",
    "audio"
]

[dev-dependencies]
assert2 = { workspace = true }



# https://github.com/rust-lang/rust/blob/master/RELEASES.md#cargo
# https://doc.rust-lang.org/nightly/cargo/reference/workspaces.html#the-dependencies-table
[workspace.dependencies]
# the good part is that i have the same version of crossterm for the entire workspace
# and if i manually change the version here its propagated to the entire workspace
# instead of manually changing the version of crossterm for every member of the workspace
# cool
crossterm = "0.25.0"
assert2 = "0.3.6"
colored = "2.0.0"
dotenv = "0.15.0"
soloud = "1.0.2"
rand = "0.8.5"


[dependencies]
ansi_term = "0.12.1"
termion = "1.5.6"
derive_builder = "0.11.2"
thiserror = "1.0.37"

pad = "0.1.6"
ansi-parser = "0.8.0"
pancurses = "0.17.0"
rand = { workspace = true }
soloud = { workspace = true }
colored = { workspace = true }
dotenv = { workspace = true }
assert2 = { workspace = true }
crossterm = { workspace = true }
getset = "0.1.2"
lazy_static = "1.4.0"


[workspace]
members = [
    "dev-ideas",
    "examples/music"
]
