[package]
name = "typeracer"
version = "0.0.1"
edition = "2021"
default-run = "typeracer"
authors = [ "alexzanderr <alexzander.dot.dev@gmail.com>" ]
exclude = [
    "python_version"
]

[dependencies.core-dev]
git = "https://github.com/alexzanderr/rust-core-dev"
features = [
    "datetime",
    "traits",
    "terminal"
]

[dev-dependencies]
assert2 = "0.3.6"

[dependencies]
ansi_term = "0.12.1"
termion = "1.5.6"
crossterm = "0.25.0"
rand = "0.8.5"
colored = "2.0.0"
derive_builder = "0.11.2"
thiserror = "1.0.37"
assert2 = "0.3.6"
pad = "0.1.6"
ansi-parser = "0.8.0"
pancurses = "0.17.0"
