[package]
name = "typeracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
termion = "1.5.6"
core-dev = { path = "../core-dev", features = ["datetime", "traits", "terminal"] }
crossterm = "0.23.1"
rand = "0.8.5"
