#
#
# this is a sample with the default values for the game
#
#

# so the secret to `no cursor flickering` is to put a higher sleep for the ui, something like 500 ms or 1 second
sleep_ms = 700
music = true


[ui]
# maybe some people will get intimidated while
# watching the WPM and playing at the same time
# some people just dont want to see `WPM dropping`
wpm = true
invisibles = true
border = "round"
