#
# Configuration - The Cargo Book
# https://doc.rust-lang.org/cargo/reference/config.html
#
#
#
#
#
# https://doc.rust-lang.org/cargo/reference/config.html#configuration-format
[alias]
b = "build"
br = "build --release"
c = "check"
t = ["test", "--", "show-output"]
r = "run"
rr = "run --release"
bn = "bench"
# space_example = ["run", "--release", "--", "\"command list\""]

[term]
# whether cargo output is quiet
quiet = false
verbose = false        # whether cargo provides verbose output
color = "always"         # whether cargo colorizes output
progress.when = "always" # whether cargo shows progress bar
progress.width = 100    # width of progress bar

[env]
# RUST_BACKTRACE = "full"
