#
#
# Configuration - The Cargo Book
# https://doc.rust-lang.org/cargo/reference/config.html

# https://doc.rust-lang.org/cargo/reference/config.html#configuration-format
[alias]
b = "build"
br = "build --release"
c= "check"
t = ["test", "--", "show-output"]
r = "run"
rr = "run --release"
# space_example = ["run", "--release", "--", "\"command list\""]

[term]
# whether cargo output is quiet
quiet = false
verbose = false        # whether cargo provides verbose output
color = 'auto'         # whether cargo colorizes output
progress.when = 'auto' # whether cargo shows progress bar
progress.width = 80    # width of progress bar

[env]
# RUST_BACKTRACE = "full"
