#
#
# Configuration - The Cargo Book
# https://doc.rust-lang.org/cargo/reference/config.html

# https://doc.rust-lang.org/cargo/reference/config.html#configuration-format
[alias]
b = "build"
c = "check"
t = ["test", "--", "show-output"]
r = "run"
rr = "run --release"
# space_example = ["run", "--release", "--", "\"command list\""]

[term]
quiet = true          # whether cargo output is quiet
verbose = false        # whether cargo provides verbose output
color = 'auto'         # whether cargo colorizes output
progress.when = 'auto' # whether cargo shows progress bar
progress.width = 80    # width of progress bar