[book]
title = "Typeracer Book - Project History, Events and Discoveries"
description = "Rust Typeracer book for explainig how API works and to share ideas"
authors = ["alexzanderr"]
language = "en"
multilingual = false
src = "src"
