[package]
name = "dev-ideas"
version = "0.0.1"
edition = "2021"


# https://doc.rust-lang.org/nightly/cargo/reference/workspaces.html#the-dependencies-table
[dependencies]
crossterm = { workspace = true }
